### ISSUE TITLE
Books returned (reso) into the warehouse have ambiguous labels

### ISSUE THREAD

**Issue by lucacontalbo** [ilmercatinodellibro/ilmercatinodellibro#104]
Steps to reproduce the error:
1) buy some books with an account;
2) return the books into the warehouse (reso);
3) go back into the warehouse panel.

![Screenshot from 2024-06-26 19-00-33](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/37805862/c8fdcb2e-cc95-4bc2-b4dd-312e89b41c25)

In the dropdown toggles the status of the book is shown as not available, while instead the book is in the warehouse.

**Comment by IlCallo** [comment]
This is due to the same reason underlying https://github.com/ilmercatinodellibro/ilmercatinodellibro/issues/159 and https://github.com/ilmercatinodellibro/ilmercatinodellibro/issues/115

This is issue is still relevant because there are a couple of "hidden" mechanism that make a book not available even if it's actually available in the warehouse

Here's the issue tracking displaying those values: https://github.com/ilmercatinodellibro/ilmercatinodellibro/issues/163

Those values are:
- the number of active reservations for that book
- the number of books blocked in a cart

**Comment by IlCallo** [comment]
This had been resolved due to all other related issues being resolved
