### ISSUE TITLE
Change the download of the receipt in only the visualization in the browser

### ISSUE THREAD

**Issue by sarapeddy** [ilmercatinodellibro/ilmercatinodellibro#128]

**Comment by IlCallo** [comment]
Related code:

https://github.com/ilmercatinodellibro/ilmercatinodellibro/blob/295c39905b25e3701e75c18803a485e3452bbd62/packages/client/src/components/manage-users/receipts-table.vue#L98-L122

https://github.com/ilmercatinodellibro/ilmercatinodellibro/blob/295c39905b25e3701e75c18803a485e3452bbd62/packages/server/src/modules/receipt/receipt.controller.ts#L17-L36

Seems like it has been defined to export the file on purpose
The whole `objectUrls` management there kinda confuses me so I wanna hear @yusufkandemir on this before just removing the whole `exportFile` part and let the browser open the PDF in another tab

**Comment by yusufkandemir** [comment]
@IlCallo the requirements stated that it should download the PDF. So, it has been implemented to download the file using `exportFile`, then fall back to `window.open` in case that does not work. `objectUrls` logic is there for the fallback logic, to avoid creating multiple Object URLs for the same file, and to be able to clean up the Object URLs afterward.

If the new aim is always opening it in the new tab, we can get rid of the `exportFile` call and the `if (success === true)` part.
We can't simply open the link directly due to authentication and authorization needs. So, we fetch it and save it to memory first, then utilize the file that way.

**Comment by IlCallo** [comment]
> We can't simply open the link directly due to authentication and authorization needs. So, we fetch it and save it to memory first, then utilize the file that way.

Yep, I guessed this part

> we can get rid of the exportFile call and the if (success === true) part.

Thanks, I needed this confirmation
