### ISSUE TITLE
Very long execution time for generate process with WSL

### ISSUE THREAD

**Issue by sarapeddy** [ilmercatinodellibro/ilmercatinodellibro#44]
Quando ho runnato pnpm server:migrate:reset, al punto in cui chiama generate ci mette molto tempo per eseguire. Al momento abbiamo disattivato quella parte settando --skip-generate dopo la prima volta.

**Comment by sarapeddy** [comment]
Anche quando si avvia in dev mode ci mette più di 5 minuti per inizializzare tutto

**Comment by SirAuron** [comment]
General comments/advices for VSL correct usage before closing this Issue. When working with WSL:
- make sure that the files on which the WSL work are stored directly inside the WSL file system and not inside the shared Windows `/mnt/` folder. This will heavily impact access time.
- Make sure that the Windows antivirus is not actively watching the files being processed by the WSL, otherwise the CPU usage will skyrocket and hard disk speed will be reduced heavily.
- Consequently, make sure to have all that is needed inside the WSL environment, save maybe for Docker which can be tunneled.

Generally speaking though, this project was developed both on MacOs by Yusuf and on Windows by me, Andrea and Alessandro with not problems whatsoever. So it can be installed and run there directly.
