### ISSUE TITLE
Login page should contain FAQ

### ISSUE THREAD

**Issue by IlCallo** [ilmercatinodellibro/ilmercatinodellibro#56]

**Comment by SirAuron** [comment]
@andrea-cerlini this is one of the things I was referring to when I wrote the [message over Discord](https://discord.com/channels/824214417956143104/844575589876236289/1239923446889185300).
Basically:
1. Take [this content](https://re.ilmercatinodellibro.com/) and place it into the `fixtures/retail-locations.ts` file for Reggio Emilia.
2. Do the same of step 1 [for Modena as well](https://mo.ilmercatinodellibro.com/).
3. Create a new field into the DB that stores these values and update the corresponding GraphQL fragments so that they now download this content too.
4. Create a dedicated component that renders the text stored inside the DB and with more or less the same stlye of the FAQ you can see on old websites. Store the style directly inside the DB fields especially for bold words. Technically it should be possibile to copy the html directly from the old websites.
5. Create a dedicated page called FAQ reachable from when a user is logged in from the top bar navigation component and from the drawer component.
6. When a user is not logged in, render the FAQ inside the login page and place that content below the login form.

(As a reference for how to do this, you can take a look at `RE_JOIN_US` field inside the `fixtures/retail-locations.ts`)

**Comment by SirAuron** [comment]
Closed in #56
